name: Codebase tests

on:
  pull_request:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-22.04, ParallelHoss]
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.runner }}-pip-${{ hashFiles('**/setup.py', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.runner }}-pip-

      - name: Run Tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .[test]
          pytest tests/
